TOP = ../..
include $(TOP)/configure/CONFIG

ADL_DIR = adl
UI_DIR  = ui/autoconvert
EDL_DIR = edl/autoconvert
OPI_DIR = opi/autoconvert
BOB_DIR = bob/autoconvert

include $(CONFIG)/RULES_DIRS

ADL2EDL = adl2edl
EDMFONTFILE = edl/fonts.adl2edl

-include $(SUPPORT)/configure/RULES_OPI
